Repository dottxt-ai/outlines-core, pull requests merged in 2025-01, with the labels that each got.

#136 fix: Generalise re_replacement_seq to deal with all cases
  python/outlines_core/fsm/regex.py
  tests/fsm/test_regex.py
Labels: bug

#138 Add support for type in json schema to be a list
  src/error.rs
  src/json_schema/mod.rs
  src/json_schema/parsing.rs
Labels: enhancement, json schema

#159 Update README
  Cargo.toml
  README.md
Labels: documentation, enhancement

#161 Update actions artifact
  .github/workflows/release_pypi.yaml
Labels: CI
